# (1) import libraries

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

import numpy as np
import time

# (2) preparing iris dataset

In [2]:
iris = datasets.load_iris()

# get training and testing indexes randomly
train_indx = np.random.choice(range(0, 150), int(iris.target.shape[0]/100*60), replace=False)
test_indx = np.array([indx for indx in np.arange(0, 150, 1) if indx not in train_indx])

x_train = iris.data[train_indx, :]
y_train = iris.target[train_indx]

x_test = iris.data[test_indx, :]
y_test = iris.target[test_indx]

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(90, 4)
(90,)
(60, 4)
(60,)


# (3) parameters estimation

In [7]:
mu_0 = np.mean(x_train[y_train == 0], axis=0)
sigma_0 = np.cov(x_train[y_train == 0], rowvar=0)
print(mu_0)
print(sigma_0)

mu_1 = np.mean(x_train[y_train == 1], axis=0)
sigma_1 = np.cov(x_train[y_train == 1], rowvar=0)
print(mu_1)
print(sigma_1)

mu_2 = np.mean(x_train[y_train == 2], axis=0)
sigma_2 = np.cov(x_train[y_train == 2], rowvar=0)
print(mu_2)
print(sigma_2)

[4.96896552 3.43103448 1.41724138 0.23103448]
[[0.15435961 0.14028325 0.02198276 0.01135468]
 [0.14028325 0.20578818 0.01408867 0.01114532]
 [0.02198276 0.01408867 0.02433498 0.00337438]
 [0.01135468 0.01114532 0.00337438 0.00793103]]
[5.89677419 2.78387097 4.22580645 1.32903226]
[[0.26765591 0.0816129  0.18841935 0.05043011]
 [0.0816129  0.09939785 0.08276344 0.0388172 ]
 [0.18841935 0.08276344 0.22664516 0.06789247]
 [0.05043011 0.0388172  0.06789247 0.03612903]]
[6.69       3.00666667 5.59333333 2.        ]
[[0.34231034 0.12455172 0.27475862 0.04034483]
 [0.12455172 0.12478161 0.11590805 0.05758621]
 [0.27475862 0.11590805 0.29788506 0.05724138]
 [0.04034483 0.05758621 0.05724138 0.07448276]]


# (4) bayesian decision making

In [5]:
gnb = GaussianNB()

y_pred = gnb.fit(x_train, y_train).predict(x_test)
print('Testing classification accuracy: %.4f' % ((y_test == y_pred).sum()/x_test.shape[0]))

Testing classification accuracy: 0.9667
